### ISSUE TITLE
"You are not authorized to access this page."

### ISSUE THREAD

**Issue by tyler36** [drunomics/lupus-nuxtjs-drupal-stack-example#37]
I get the following error when trying to access the front:

`You are not authorized to access this page.`

The backend server appears to be working. IE. When I visit `https://lupus-nuxtjs-drupal-stack-example.ddev.site/` I see "Welcome to Lupus Nuxt.js Drupal Stack"

The front end appears to be working.  IE. Console displays

```shell
ℹ Waiting for file changes                                                                                                                       13:45:53
ℹ Memory usage: 168 MB (RSS: 296 MB)                                                                                                             13:45:53
ℹ Listening on: http://localhost:38881/  
```

However, when I access `http://localhost:38881` I get the error. What could I be mssing?

**Comment by neurotic** [comment]
The same thing happens to me. Did you find the solution @tyler36?

**Comment by tyler36** [comment]
@neurotic no, I haven't found a solution yet.

**Comment by tyler36** [comment]
Closing. 

Project appears abandoned.
