### ISSUE TITLE
Frontpage is set to /node/2 but no content is provided

### ISSUE THREAD

**Issue by beatchristen** [drunomics/lupus-nuxtjs-drupal-stack-example#4]
https://github.com/drunomics/lupus-nuxtjs-drupal-stack-example/blob/f3d9210f7002f088dcbfae979e47bad8beeb7e3d/config/system.site.yml#L8

Not sure if my site-install failed and the content IS there or if this is work in progress:
To get a better first impression, adding some demo content for the configured nodes would be appreciated!

**Comment by fago** [comment]
Good point. Maybe it would be a good idea to set the frontpage to simply /admin/content meanwhile?

**Comment by fago** [comment]
done so.
